// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3aUVxPFshMyE70jaXPajcAakjFWFm98',
    appId: '1:1094765801191:web:50d43318e4d9a62a6bbc42',
    messagingSenderId: '1094765801191',
    projectId: 'fitnessapp-90074',
    authDomain: 'fitnessapp-90074.firebaseapp.com',
    storageBucket: 'fitnessapp-90074.firebasestorage.app',
    measurementId: 'G-5T2P7QE38F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VOyVy-J-EZ3_Y5PujxnEiof9ohhpUSQ',
    appId: '1:1094765801191:android:bdb69321a61195116bbc42',
    messagingSenderId: '1094765801191',
    projectId: 'fitnessapp-90074',
    storageBucket: 'fitnessapp-90074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6amlFidmzuuKKE8FJegH4tsVbW5TB9i8',
    appId: '1:1094765801191:ios:e857d95c5c2deb226bbc42',
    messagingSenderId: '1094765801191',
    projectId: 'fitnessapp-90074',
    storageBucket: 'fitnessapp-90074.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6amlFidmzuuKKE8FJegH4tsVbW5TB9i8',
    appId: '1:1094765801191:ios:e857d95c5c2deb226bbc42',
    messagingSenderId: '1094765801191',
    projectId: 'fitnessapp-90074',
    storageBucket: 'fitnessapp-90074.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW3aUVxPFshMyE70jaXPajcAakjFWFm98',
    appId: '1:1094765801191:web:0b5e4cbd76ad781c6bbc42',
    messagingSenderId: '1094765801191',
    projectId: 'fitnessapp-90074',
    authDomain: 'fitnessapp-90074.firebaseapp.com',
    storageBucket: 'fitnessapp-90074.firebasestorage.app',
    measurementId: 'G-6PMES14XVZ',
  );
}
